import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./_ui/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const meta = {
  favicon: "/icon.svg",
  title: "Mango Entertainment",
  description: "Generated by the best coders who eat mangoes",
  url: "https://mango-entertainment-alexvcs.vercel.app/",
  type: "website",
};

export const metadata = {
  title: meta.title,
  description: meta.description,
  favicon: meta.favicon,
  url: meta.url,
  openGraph: {
    url: meta.url,
    title: meta.title,
    description: meta.description,
    type: meta.type,
    site_name: meta.title,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`font-sans ${inter.variable} bg-entertainment-dark-blue grid h-screen grid-cols-1 lg:grid-cols-[160px_1fr]`}
        >
          <TRPCReactProvider>
            <Navbar />
            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
